### ISSUE TITLE
setPanel function gone

### ISSUE THREAD

**Issue by Blame4** [Autodesk-Forge/forge-extensions#7]
![image](https://user-images.githubusercontent.com/40301148/108789797-08f98500-75b6-11eb-9e5e-1eba96a1f19b.png)
I just found customproperty not working. It turns out the setpanel function is gone in the latest documentation.

**Comment by Alex-Dell1** [comment]
Just found out the same issue. Is there a valid alternative?

**Comment by adamenagy** [comment]
I'm checking with engineering to get the documentation fixed. You can see that `setPanel()` is still in the source code (https://developer.api.autodesk.com/modelderivative/v2/viewers/7.*/viewer3D.js) and the extension works fine. Perhaps it was a temporary issue a year or so ago?
![image](https://user-images.githubusercontent.com/2300154/189608114-cec53eae-17b0-447b-a7bb-3425864fa907.png)
